### ISSUE TITLE
Getting a date parse Exception using at ch.compile.recaptcha.ReCaptchaVerify.verify(ReCaptchaVerify.java:76)

### ISSUE THREAD

**Issue by joethejones** [KeeTraxx/recaptcha#1]
Not sure this is anything to do with your code, and it may well be a response change from Google, but is there any reason we would be getting this?

It's for the noCaptcha, v2, response looks fine, it's verifying OK on the client side.

com.google.gson.JsonSyntaxException: java.text.ParseException: Unparseable date: "2018-03-05T11:36:39Z"
	at com.google.gson.DefaultTypeAdapters$DefaultDateTypeAdapter.deserialize(DefaultTypeAdapters.java:281)
	at com.google.gson.DefaultTypeAdapters$DefaultDateTypeAdapter.deserialize(DefaultTypeAdapters.java:243)
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:50)
	at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:88)
	at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:116)
	at com.google.gson.ObjectNavigator.navigateClassFields(ObjectNavigator.java:158)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:131)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:73)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:568)
	at com.google.gson.Gson.fromJson(Gson.java:515)
	at com.google.gson.Gson.fromJson(Gson.java:484)
	at com.google.gson.Gson.fromJson(Gson.java:434)
	at com.google.gson.Gson.fromJson(Gson.java:406)
	at ch.compile.recaptcha.ReCaptchaVerify.verify(ReCaptchaVerify.java:76)

**Comment by KeeTraxx** [comment]
Seems like Gson has problems deserializing the incoming json. I'll have a look at it later and get back to you.

**Comment by joethejones** [comment]
I implemented my own method in the end, using the SimpleDateFormat (ouch I know);

```
JsonElement jelement = new JsonParser().parse(responseBody);
JsonObject job = jelement.getAsJsonObject();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
sdf.setTimeZone(TimeZone.getTimeZone("GMT"));
```
